<html>
	<body>
		<h2><b>Verify your e-mail!</b></h2>
		<h4><b>Hi ${firstName}</b></h4>
		<p style='padding:10px; text-align:justify;'>
			We welcome you to Egozz, Experience the Emphasized Gentle of Zen & Zappy Trips !<br>
			<b>Please Verify your e-Mail by using the code given below</b>
			<h2 style='text-align:center;'>CODE : ${otp} </h2>
			
		</p>
		<p style='padding:10px; text-align:justify; color:rgb(192,39,45);'>
			The code will be valid for next 2 hours only !
		</p>
		<h3>Happy Travelling !</h3>
		<h4>Team EGOZZ</h4>
	</body>
</html>