<html>
	<body>
		<h2><b>Trip Request for ${startDate} !</b></h2>
		<h4><b>Hey ${firstName}</b></h4>
		<p style='padding:10px; text-align:justify;'>
			This is to inform you that you have a trip request for ${vehicleName} starting ${startDate} to ${endDate}.<br>
			This request had been made by ${userFullName} & can be contacted on ${userPhone}
			<br><b>Please submit your acceptance for the trip ASAP !</b>
		</p>
		<h3>Regards</h3>
		<h4>Team EGOZZ</h4>
	</body>
</html>